# Generated by Django 4.1.2 on 2022-10-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_price', models.CharField(max_length=30)),
                ('project_images', models.ImageField(upload_to='images/file')),
                ('project_Files', models.FileField(null=True, upload_to='important')),
                ('server_site', models.CharField(max_length=100)),
                ('Client_Side', models.CharField(max_length=100)),
                ('DataBase', models.CharField(max_length=100)),
                ('project_desc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Projects_ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name', models.CharField(max_length=150)),
            ],
        ),
    ]
