# Generated by Django 4.1.2 on 2022-10-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Docment_word', models.FileField(upload_to='Docu')),
                ('Document_name', models.CharField(max_length=100)),
                ('Document_desc', models.CharField(max_length=300)),
                ('Document_price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ppt_word', models.FileField(upload_to='PPT')),
                ('Ppt_name', models.CharField(max_length=100)),
                ('Ppt_desc', models.CharField(max_length=300)),
                ('Ppt_price', models.CharField(max_length=50)),
            ],
        ),
    ]
